### ISSUE TITLE
Image Optimizations

### ISSUE THREAD

**Issue by mattsp1290** [mattsp1290/alpine-rails#1]
Per Slack conversation with @kbluescode
one piece of advice for this image, is that you probably don't want all your dependencies as full-on ENV vars, since those will persist on run

[12:41 PM]
I use ARG for that instead, that way they're only involved in the build process

[12:41 PM]
and another cool thing with alpine, there's a super easy way to install stuff without it persisting to the cache

[12:41 PM]
`apk add --no-cache`, then you don't have to clean anything up afterwards :slightly_smiling_face:

[12:43 PM]
and as another style thing, this is totally just me, but I just use the COPY command to add in my custom .gemrc files and configs, that way I don't need to echo them in the dockerfile

[12:44 PM]
keeps things a bit slimmer, plus COPY does checksums on the files, so it'll redo them if it changes

[12:45 PM]
another thing, these lines look redundant:
```gem install -N nokogiri -- --use-system-libraries && \
...
bundle config --global build.nokogiri  "--use-system-libraries" && \
```

[12:45 PM]
since nokogiri will be installed with a bundle install later anyways, which is now configured to use the system libraries (that said, this is ruby, there may be some weirdness around the install, in which case, that's totes cool)

[12:46 PM]

**Comment by kbluescode** [comment]
@mattsp1290 - so organized!

**Comment by mattsp1290** [comment]
Created PR https://github.com/mattsp1290/alpine-rails/pull/2 @kbluescode could you please review at your leisure
